### ISSUE TITLE
Semaphore [swift-lazy-property-initialization]

### ISSUE THREAD

**Issue by District-Dev** [PureMVC/puremvc-java-multicore-framework#3]
sem_init=Init(sem, val),

   function Init(semaphore sem, int val){
 	disable_interrupt;
 	sem.K = val;
 	enable_interrupt;
 }
sem_wait=P(sem),

   function P(semaphore sem){
 	disable_interrupt;
 	if (sem.K <= 0){
 		L.suivant = processus_courant;
 		processus_courant.état = bloque;
 		reordonnancement = vrai;
 	}
 	sem.K = sem.K - 1;
 	enable_interrupt;
 }
sem_post=V(sem)

   function V(semaphore sem){
 	disable_interrupt;
 	sem.K = sem.K+1;
 	if (not L.vide){
 		processus_réveillé = L.tête;
 		processus_réveillé.état = prêt;
 		reordonnancement = vrai;
 	}
 	enable_interrupt;
 }

**Comment by saadshams** [comment]
Irrelevant.

**Comment by District-Dev** [comment]
Formats des modèles de documents ODF
	
		
			Type de fichier
			Extension
			Type MIME
		
		
			Texte formaté
			.ott
			application/vnd.oasis.opendocument.text-template
		
		
			Tableur
			.ots
			application/vnd.oasis.opendocument.spreadsheet-template
		
		
			Présentation
			.otp
			application/vnd.oasis.opendocument.presentation-template
		
		
			Dessin
			.otg
			application/vnd.oasis.opendocument.graphics-template
		
	


 

Envoyé: vendredi 8 mars 2019 à 03:23
De: "Saad" <notifications@github.com>
À: PureMVC/puremvc-java-multicore-framework <puremvc-java-multicore-framework@noreply.github.com>
Cc: District-Dev <district_dev@graphic-designer.com>, Author <author@noreply.github.com>
Objet: Re: [PureMVC/puremvc-java-multicore-framework] Semaphore [swift-lazy-property-initialization] (#3)


Closed #3.
